[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
reproducible = false

[tool.hatch.build.targets.wheel]
packages = ["webapp/"]


[project]
name = "pramari-webapp"
version = "1.1.23"
authors = [
  { name="Andreas Neumeier", email="andreas@neumeier.org" },
]
description = "Authentication and Userprofiles in  pramari.de"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "django>=4.2",
  "django-allauth",
  # "django-activity-stream",
  "django-oauth-toolkit",
  "djangorestframework",
  "Pillow",
  "pyyaml",
  "celery"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://www.pramari.de"
"Bug Tracker" = "https://github.com/pramari/apc/issues"

# [tool.pytest.ini_options]
# addopts = "" #--cov --cov-report html --cov-report term-missing --cov-fail-under 95"

[tools.tox]

[tool.coverage.run]
source = ["src"]


