# Generated by Django 5.1.6 on 2025-04-02 14:39

import django.db.models.deletion
import django.utils.timezone
import uuid
import webapp.activitypub.models.action
import webapp.activitypub.models.actor
import webapp.activitypub.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("webapp", "0051_alter_actor_unique_together_remove_actor_follows_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_object_id", models.CharField(db_index=True, max_length=255)),
                (
                    "activity_type",
                    models.CharField(
                        choices=webapp.activitypub.models.action.get_activity_types,
                        db_index=True,
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "target_object_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "action_object_object_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("public", models.BooleanField(db_index=True, default=True)),
                (
                    "action_object_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_object",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "actor_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actor",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[webapp.activitypub.validators.validate_iri],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=webapp.activitypub.models.actor.get_actor_types,
                        default="Person",
                        max_length=255,
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actor (Activity Streams 2.0)",
                "verbose_name_plural": "Actors (Activity Streams 2.0)",
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "accepted",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[webapp.activitypub.validators.validate_iri],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actor",
                        to="activitypub.actor",
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object",
                        to="activitypub.actor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="actor",
            name="follows",
            field=models.ManyToManyField(
                blank=True,
                related_name="followed_by",
                through="activitypub.Follow",
                to="activitypub.actor",
            ),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "object",
                    models.URLField(validators=[webapp.activitypub.validators.validate_iri]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activitypub.actor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("remoteID", models.URLField(blank=True, db_index=True, null=True)),
                ("content", models.TextField()),
                ("contentMap", models.JSONField(blank=True, null=True)),
                (
                    "published",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("public", models.BooleanField(db_index=True, default=True)),
                ("sensitive", models.BooleanField(db_index=True, default=False)),
                (
                    "attributedTo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activitypub.actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note (Activity Streams 2.0)",
                "verbose_name_plural": "Notes (Activity Streams 2.0)",
            },
        ),
        migrations.AlterUniqueTogether(
            name="actor",
            unique_together={("id", "type", "profile")},
        ),
    ]
