# Generated by Django 4.2.1 on 2023-05-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0007_profile_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="icon",
            field=models.CharField(
                choices=[("0s", "0-square")], default="0s", max_length=2
            ),
        ),
    ]
