# Generated by Django 5.0.4 on 2024-06-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0020_alter_note_options_note_sensitive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="ap_id",
            field=models.CharField(
                blank=True, help_text="ActivityPub ID", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="private_key_pem",
            field=models.TextField(blank=True, help_text="Private Key"),
        ),
    ]
