# Generated by Django 5.0.4 on 2024-06-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0022_profile_key_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="key_id",
            field=models.CharField(
                blank=True, help_text="Key ID", max_length=255, unique=True
            ),
        ),
    ]
