# Generated by Django 5.0.4 on 2024-06-13 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0023_alter_profile_key_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="key_id",
        ),
    ]
