# Generated by Django 5.0.4 on 2024-06-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0024_remove_profile_key_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="ap_id",
            field=models.CharField(
                blank=True,
                help_text="ActivityPub ID",
                max_length=255,
                unique=True,  # noqa: E501
            ),
        ),
    ]
