# Generated by Django 5.0.4 on 2024-06-24 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0026_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.profile",
            ),
        ),
    ]
