# Generated by Django 5.0.4 on 2024-06-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0027_alter_actor_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="preferredUsername",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
