# Generated by Django 5.0.4 on 2024-06-27 09:31

# import webapp.models.activitypub.action
import webapp.activitypub.models.action
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0029_actor_follows"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="verb",
        ),
        migrations.AddField(
            model_name="action",
            name="activity_type",
            field=models.CharField(
                choices=webapp.activitypub.models.action.get_activity_types,
                db_index=True,
                default="add",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
