# Generated by Django 5.0.4 on 2024-07-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0031_alter_actor_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actor",
            name="preferredUsername",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="slug",
        ),
    ]
