# Generated by Django 5.0.4 on 2024-07-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0032_remove_actor_preferredusername_remove_actor_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="id",
            field=models.URLField(
                max_length=255, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
