# Generated by Django 5.0.4 on 2024-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0034_alter_actor_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actor",
            name="follows",
        ),
        migrations.AddField(
            model_name="actor",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="webapp.actor"
            ),
        ),
    ]
