# Generated by Django 5.0.7 on 2024-07-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0038_alter_like_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actor",
            old_name="following",
            new_name="follows",
        ),
    ]
