# Generated by Django 5.0.7 on 2024-07-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0039_rename_following_actor_follows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="follows",
            field=models.ManyToManyField(
                blank=True, related_name="followed_by", to="webapp.actor"
            ),
        ),
    ]
