# Generated by Django 5.0.7 on 2024-08-11 15:14

import django.db.models.deletion
import uuid
import webapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0043_remove_actor_follows"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actor",
            name="flw",
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "accepted",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[webapp.validators.validate_iri],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actor",
                        to="webapp.actor",
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object",
                        to="webapp.actor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="actor",
            name="follows",
            field=models.ManyToManyField(
                blank=True,
                related_name="followed_by",
                through="webapp.Follow",
                to="webapp.actor",
            ),
        ),
        migrations.DeleteModel(
            name="Fllwng",
        ),
    ]
