# Generated by Django 5.0.7 on 2024-08-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0044_remove_actor_flw_follow_actor_follows_delete_fllwng"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="ap_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="follows",
        ),
    ]
