# Generated by Django 5.0.7 on 2024-08-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0047_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="consent",
        ),
        migrations.RemoveField(
            model_name="user",
            name="public",
        ),
    ]
