# Generated by Django 5.1.6 on 2025-03-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0049_profile_publish_to_linkedin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="img",
            field=models.ImageField(
                default="/user/default.png", upload_to="mediafiles/user/"
            ),
        ),
    ]
