# Generated by Django 5.1.6 on 2025-04-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0050_alter_profile_img"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="actor",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="actor",
            name="follows",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="actor",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="object",
        ),
        migrations.RemoveField(
            model_name="note",
            name="attributedTo",
        ),
        migrations.RemoveField(
            model_name="like",
            name="actor",
        ),
        migrations.DeleteModel(
            name="Action",
        ),
        migrations.DeleteModel(
            name="Follow",
        ),
        migrations.DeleteModel(
            name="Note",
        ),
        migrations.DeleteModel(
            name="Actor",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
