# Generated by Django 3.2.10 on 2022-01-04 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def move_profile(apps, schema_editor):
    User = apps.get_model('webapp', 'User')
    Profile = apps.get_model('webapp', 'Profile')
    for user in User.objects.all():
        profile = Profile()
        profile.user = user
        profile.dob = user.dob
        profile.public = user.public
        profile.consent = user.consent
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('consent', models.BooleanField(default=False)),
                ('dob', models.DateField(blank=True, null=True)),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='webapp.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(move_profile),
    ]
