# Generated by Django 4.2.1 on 2023-05-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0008_profile_bio_profile_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor", models.URLField()),
                ("verb", models.CharField(max_length=255)),
                ("object", models.URLField()),
                ("target", models.URLField(blank=True, null=True)),
                ("published", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="public_key_pem",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="img",
            field=models.ImageField(
                default="//storage.cloud.google.com/media.pramari.de/user/default.png",
                upload_to="mediafiles/user/",
            ),
        ),
    ]
