# Generated by Django 4.2.1 on 2023-05-24 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0009_activity_profile_public_key_pem_alter_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="verb",
            field=models.CharField(
                choices=[
                    ("Accept", "Accept"),
                    ("Add", "Add"),
                    ("Announce", "Announce"),
                    ("Arrive", "Arrive"),
                    ("Block", "Block"),
                    ("Create", "Create"),
                    ("Delete", "Delete"),
                    ("Dislike", "Dislike"),
                    ("Flag", "Flag"),
                    ("Follow", "Follow"),
                    ("Ignore", "Ignore"),
                    ("Invite", "Invite"),
                    ("Join", "Join"),
                    ("Leave", "Leave"),
                    ("Like", "Like"),
                    ("Listen", "Listen"),
                    ("Move", "Move"),
                    ("Offer", "Offer"),
                    ("Question", "Question"),
                    ("Read", "Read"),
                    ("Reject", "Reject"),
                    ("Remove", "Remove"),
                    ("TentativeReject", "TentativeReject"),
                    ("TentativeAccept", "TentativeAccept"),
                    ("Travel", "Travel"),
                    ("Undo", "Undo"),
                    ("Update", "Update"),
                    ("View", "View"),
                ],
                max_length=255,
            ),
        ),
    ]
