# Generated by Django 4.2.1 on 2023-05-26 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0010_alter_activity_actor_alter_activity_verb"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_type", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("name", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="private_key_pem",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("Article", "Article"),
                            ("Note", "Note"),
                            ("Image", "Image"),
                            ("Video", "Video"),
                            ("Audio", "Audio"),
                        ],
                        max_length=255,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("published", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "attachment",
                    models.ManyToManyField(blank=True, to="webapp.attachment"),
                ),
                (
                    "attributed_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "in_reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.object",
                    ),
                ),
            ],
        ),
    ]
