# Generated by Django 4.2.1 on 2023-05-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0011_attachment_profile_private_key_pem_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="actor",
            field=models.CharField(max_length=255),
        ),
    ]
