# Generated by Django 4.2.1 on 2023-05-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_activity_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ap_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
