# Generated by Django 4.2.7 on 2024-01-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0015_alter_profile_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Activity",
        ),
        migrations.RemoveField(
            model_name="object",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="object",
            name="attributed_to",
        ),
        migrations.RemoveField(
            model_name="object",
            name="in_reply_to",
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="Attachment",
        ),
        migrations.DeleteModel(
            name="Object",
        ),
    ]
