# Generated by Django 5.0.3 on 2024-03-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0015_alter_profile_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Activity",
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, help_text="Short Bio"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="consent",
            field=models.BooleanField(
                default=False, help_text="Consent to store and use data."
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="dob",
            field=models.DateField(
                blank=True, help_text="Date of Birth (DOB)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gravatar",
            field=models.BooleanField(
                default=True, help_text="Use Gravatar profile image."
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",  # noqa: E501
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="img",
            field=models.ImageField(
                default="https://storage.cloud.google.com/media.pramari.de/user/default.png",  # noqa: E501
                upload_to="mediafiles/user/",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="public",
            field=models.BooleanField(
                default=False, help_text="Make Profile Profile public?"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="public_key_pem",
            field=models.TextField(blank=True, help_text="Public Key"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=models.SlugField(help_text="Slug", null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",  # noqa: E501
            ),
        ),
        migrations.DeleteModel(
            name="Attachment",
        ),
        migrations.DeleteModel(
            name="Object",
        ),
    ]
