# Generated by Django 5.0.3 on 2024-03-04 19:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("webapp", "0016_delete_activity_remove_object_attachment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("public", models.BooleanField(db_index=True, default=True)),
                (
                    "actor_object_id",
                    models.CharField(db_index=True, max_length=255),
                ),  # noqa: E501
                ("verb", models.CharField(db_index=True, max_length=255)),
                (
                    "actor_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actor",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
