# Generated by Django 5.0.4 on 2024-06-24 10:40

import django.db.models.deletion
from django.db import migrations, models


def create_actor(apps, schema_editor):
    Profile = apps.get_model("webapp", "Profile")
    Actor = apps.get_model("webapp", "Actor")

    for profile in Profile.objects.all():
        Actor.objects.create(id=profile.ap_id, profile=profile)


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0025_alter_profile_ap_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,  # noqa: E501
                    ),
                ),
                ("type", models.CharField(default="Person", max_length=255)),
                ("slug", models.SlugField(help_text="Slug", null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actor (Activity Streams 2.0)",
                "verbose_name_plural": "Actors (Activity Streams 2.0)",
                "unique_together": {("id", "type", "profile")},
            },
        ),
        migrations.RunPython(create_actor),
    ]
