# Generated by Django 5.0.4 on 2024-07-11 07:52

import webapp.models.actor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0030_remove_action_verb_action_activity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="type",
            field=models.CharField(
                choices=webapp.models.actor.get_actor_types,
                default="Person",
                max_length=255,
            ),
        ),
    ]
