# Generated by Django 5.0.7 on 2024-07-21 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0035_remove_actor_follows_actor_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="attributedTo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.actor",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="contentMap",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="remoteID",
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
    ]
