# Generated by Django 5.0.7 on 2024-08-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0041_alter_actor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="flw",
            field=models.ManyToManyField(
                blank=True, related_name="flwng", to="webapp.actor"
            ),
        ),
    ]
