# Generated by Django 5.0.7 on 2024-08-10 15:36

import django.db.models.deletion
import webapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0041_alter_actor_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fllwng",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[webapp.validators.validate_iri],
                    ),
                ),
                (
                    "accepted",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[webapp.validators.validate_iri],
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actor",
                        to="webapp.actor",
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object",
                        to="webapp.actor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="actor",
            name="flw",
            field=models.ManyToManyField(
                blank=True,
                related_name="flwng",
                through="webapp.Fllwng",
                to="webapp.actor",
            ),
        ),
    ]
