# Generated by Django 5.0.7 on 2024-08-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0042_fllwng_actor_flw"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actor",
            name="follows",
        ),
    ]
